# -*- coding: utf-8 -*-
"""Data_Analysis_Python_Project_(Insights).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JHXRKhiLRWldQiPVgq5fS09EDGzENTBl

<a href="https://colab.research.google.com/github/sabrinavaz/portfolio/blob/master/Data_Analysis_Python_Project_(Insights).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Insights - Analisando Dados com Python

### Case - Cancelamento de Clientes

Você foi contratado por uma empresa com mais de 800 mil clientes para um projeto de Dados. Recentemente a empresa percebeu que da sua base total de clientes, a maioria são clientes inativos, ou seja, que já cancelaram o serviço.

Precisando melhorar seus resultados ela quer conseguir entender os principais motivos desses cancelamentos e quais as ações mais eficientes para reduzir esse número.

Base de dados e arquivos: https://drive.google.com/file/d/1Cwwmy5BtKOX9c48IpGE8nfiqSABeVh10/view?usp=sharing
"""

# !pip install pandas numpy openpyxl ipykernel plotly nbformat

# Importar base de dados
import pandas as pd

tabela = pd.read_csv("cancelamentos.csv")

#Visualizar base de dados
tabela = tabela.drop(columns="CustomerID")
#print(tabela)

#null and non-null values
#print(tabela.info())
tabela = tabela.dropna() #NaN not a number, valor vazio, exclui linhas
print(tabela.info())

#Cancelation Analysis
print(tabela["cancelou"].value_counts()) #contar os valores de cancelamento

print(tabela["cancelou"].value_counts(normalize=True).map("{:.1%}".format)) # % de cancelamentos, map formatacao uma casa dec

#Cancelation Cause Analysis
import plotly.express as px
#cria
for coluna in tabela.columns: #criar um grafico para cada coluna

  grafico = px.histogram(tabela, x=coluna, color="cancelou") #qntd de cliente que tem n idade
  #exibe
  #grafico.show()

tabela = tabela[tabela["duracao_contrato"]!="Monthly"] #sem duracao do contrato mensal
tabela = tabela[tabela["ligacoes_callcenter"]<=4] #sem ligacao do call center acima de 4
tabela = tabela[tabela["dias_atraso"]<=20] #sem atraso de pagamento

print(tabela["cancelou"].value_counts(normalize=True))